Sprint2
infabeti/APP-Arkaitz-Asier-David-Lopez-y-Unai-Garcia- pull request #2
Opened 2021-05-12 07:51 UTC by Asierhernandezga

Hemos terminado el sprint 2 de la APP, hacemos el pull request

2021-05-12 08:54 UTC, bmoncalvillo commented
catch (SQLException e) {
			e.printStackTrace();
		}
Revisad el control de excepciones para que :
1.- Se advierta al usuario del error que se ha producido un error (por ejemplo de conexión a la Base de Datos, en lugar de mostrar la traza del stack
2.- El programa progrese o finalice de forma adecuada teniendo cuidado de cerrar conexiones abiertas, ficheros abiertos etc...
Ejemplo:
FileInputStream inputStream = null;
    try {
        File file = new File("./tmp.txt");
        inputStream = new FileInputStream(file);

        // use the inputStream to read a file

    } catch (FileNotFoundException e) {
        System.out.println("Fichero no encontrado");
        // log.error(e);
    } finally {
        if (inputStream != null) {
            try {
                inputStream.close();
            } catch (IOException e) {
                log.error(e);
            }
        }
    }

2021-05-13 15:06 UTC, infabeti commented on Equipo2BigData/.classpath
> -	<classpathentry kind="lib" path="librerias/BBDD-2021.4.30.141952.jar"/>
Si lo quitais del classpath, también lo teneis que quitar de la carpeta. Borrad los jar antiguos.

2021-05-13 15:07 UTC, infabeti commented on Equipo2BigData/src/main/java/Controlador/ControladorPanelAnalisis.java
> +	public String[][] accionadoBottonMostrarProdLocal(String NIF) {
Este método es demasiado largo. Reducidlo.

2021-05-13 15:07 UTC, infabeti commented on Equipo2BigData/src/main/java/Controlador/ControladorPanelAnalisis.java
> +	public String[][] accionadoBottonMostrarProdGeneral() {
+1

2021-05-13 15:09 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/Combinacion.java
> +public class Combinacion {
Esta clase debería de tener un nombre más representativo

2021-05-13 15:10 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/ConsultasActividades.java
> +	public Combinacion[] conseguirDatosNaiveBayes(String NIF) {
No es recomendable hacer métodos tan largos

2021-05-13 15:11 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/ConsultasActividades.java
> +	public void ejecutarNaiveBayes(String NIF) {
Demasiadas lineas

2021-05-13 15:12 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/ConsultasSimples.java
> +			PreparedStatement st = null;
Haced un método con esas tres lineas que siempre las estais repitiendo.

2021-05-13 15:13 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/ConsultasSimples.java
> +					.prepareStatement(sentenciasBBDD.NOMBRECODIGO);
También haría un metodo para esto

2021-05-13 15:13 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/Escritor.java
> +public class Escritor {
Buscad un nombre mejor

2021-05-13 15:14 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/Escritor.java
> +	public Escritor() {}
Esto no hace falta. Borradlo.

2021-05-13 15:17 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/Modelo.java
>  	private ListaPlatos listaTemporalPlatos = new ListaPlatos();
Ya que estaís inicilializando Escritor en el constructor, esto también se debería de hacer ahí. Haced lo que decidais, pero, ceñiros a una norma de código. Siempre de una única manera.

2021-05-13 15:18 UTC, infabeti commented on Equipo2BigData/src/main/java/Vista/PanelAnalisis.java
> +		//scrollPane.setViewportView(listaProductos);
Borradlo

2021-05-13 15:20 UTC, infabeti requested changes
Os he puesto unos comentarios menores. Yo creo que os daría tiempo a incluir algún algoritmo adicional.

2021-05-13 16:41 UTC, Unai-GarciaGi commented on Equipo2BigData/.classpath
> -	<classpathentry kind="lib" path="librerias/BBDD-2021.4.30.141952.jar"/>
Eliminados

2021-05-13 16:41 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Controlador/ControladorPanelAnalisis.java
> +	public String[][] accionadoBottonMostrarProdLocal(String NIF) {
Reducido

2021-05-13 16:41 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Controlador/ControladorPanelAnalisis.java
> +	public String[][] accionadoBottonMostrarProdGeneral() {
Reducido

2021-05-13 16:41 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/Combinacion.java
> +public class Combinacion {
Cambiado

2021-05-13 17:57 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/ConsultasActividades.java
> +	public Combinacion[] conseguirDatosNaiveBayes(String NIF) {
Arreglado

2021-05-13 17:57 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/ConsultasActividades.java
> +	public void ejecutarNaiveBayes(String NIF) {
Arreglado

2021-05-13 17:57 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/ConsultasSimples.java
> +			PreparedStatement st = null;
Arreglado

2021-05-13 17:58 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/ConsultasSimples.java
> +					.prepareStatement(sentenciasBBDD.NOMBRECODIGO);
Arreglado junto a lo de arriba

2021-05-13 17:58 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/Escritor.java
> +public class Escritor {
Arreglado

2021-05-13 17:59 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/Escritor.java
> +	public Escritor() {}
Borrado

2021-05-13 17:59 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/Modelo.java
>  	private ListaPlatos listaTemporalPlatos = new ListaPlatos();
Arreglado

2021-05-13 17:59 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Vista/PanelAnalisis.java
> +		//scrollPane.setViewportView(listaProductos);
Eliminado

2021-05-14 10:44 UTC, infabeti commented on Equipo2BigData/src/main/java/Controlador/ControladorPanelAnalisis.java
> +			Calendar cal = Calendar.getInstance();
Estas lineas las estais repitiendo en ambos metodos. Agrupalos en un método.

2021-05-14 10:46 UTC, infabeti commented on Equipo2BigData/src/main/java/Modelo/ManejadorFicheros.java
> +			fich.write("\n"+historicoGeneral[i][0]+","+historicoGeneral[i][1]+","+historicoGeneral[i][2]+","+historicoGeneral[i][3]);
Haz un metodo con las lineas repetidas

2021-05-14 10:47 UTC, infabeti requested changes
Os he agregado un par de comentarios menores. Pero, el pull request está ya casi terminado. Habeis pensado en implementar algún algoritmo extra?

2021-05-14 10:48 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Controlador/ControladorPanelAnalisis.java
> +			Calendar cal = Calendar.getInstance();
Arreglado

2021-05-14 11:09 UTC, Unai-GarciaGi commented on Equipo2BigData/src/main/java/Modelo/ManejadorFicheros.java
> +			fich.write("\n"+historicoGeneral[i][0]+","+historicoGeneral[i][1]+","+historicoGeneral[i][2]+","+historicoGeneral[i][3]);
Solucionado, todo se hace ahora en el mismo método

2021-05-14 12:12 UTC, infabeti approved these changes

2021-05-15 19:18 UTC, bmoncalvillo approved these changes

2021-05-17 06:04 UTC, merged